### ISSUE TITLE
NPM Module not installing dependencies

### ISSUE THREAD

**Issue by antoniobrandao** [IjzerenHein/famous-map#11]
Hello,

I've installed famous-map like this:

    npm install famous-map --save-dev

And when I run it, using this:

    var MapView = require('famous-map/MapView');

I get this error in the console:

    Error: Cannot find module 'deamdify' from '/Users/antoniobrandao/WEBROOT/vv_app/node_modules/famous-map'

Looking at the node_modules folder, I saw that the dependencies are not being installed:

http://cl.ly/image/3n1Q082w0n25

**Comment by antoniobrandao** [comment]
It seems to me, by looking at other NPM modules in my project, that NPM modules by default install the dependencies listed in "dependencies", but not those in "devDependencies".

If this is right, moving "deamdify" to "dependencies" instead of "devDependencies" will solve this. Famous-map didn't complain about the other modules after I installed "deamdify" separately.

**Comment by antoniobrandao** [comment]
I've made a pull request with this change to save you the hassle if you approve of it.

**Comment by IjzerenHein** [comment]
Hi, thanks for pointing this out!

I just did a little bit of research and I'm pretty sure I can remove all of those dependencies entirely. I'll make the change, if you could test with the new package.json and verify that it works for you, that would be awesome. I'll make the commit and share the link here.

**Comment by IjzerenHein** [comment]
Updated package.json:
https://github.com/IjzerenHein/famous-map/commit/93d63a777047d6e91673b8dc0f0dad47e599dcbd

**Comment by antoniobrandao** [comment]
Can you please update/re-publish the NPM module? It doesn't have the new package.json yet

**Comment by antoniobrandao** [comment]
But before doing that you might want to look at this one https://github.com/IjzerenHein/famous-map/issues/13 :)

**Comment by IjzerenHein** [comment]
Hi, I've just released a new version without the unnecessary browserify dependencies. Let me know how this works out for you. Cheers

**Comment by antoniobrandao** [comment]
Thanks so much for your dedication to this awesome module. I will answer to this thread later tonight after testing.

**Comment by IjzerenHein** [comment]
Awesome, let me know how it works out.
