### ISSUE TITLE
Variable falling of of scope in CommonJS environment

### ISSUE THREAD

**Issue by antoniobrandao** [IjzerenHein/famous-map#13]
Hello, this variable:

    _globalMapViewId

Is returning undefined in my CommonJS / Browserify environment. Simply returns undefined because it seems to be declared out of scope.

    MapView.js:30 Uncaught ReferenceError: _globalMapViewId is not defined

It is declared just before the "define" -> http://cl.ly/image/0d0d3s2b0S23

-----

If I move it's declaration into inside the constructor, then the map works and I get no errors: http://cl.ly/image/2a3K2B1P2t3s

But I'm not sure if that could break some functionality elsewhere.

**Comment by IjzerenHein** [comment]
Hi, I've fixed this issue and just released a new version for it.
This should fix your problem, let me know if it doesn't.

**Comment by antoniobrandao** [comment]
Thanks I will try it tonight

**Comment by antoniobrandao** [comment]
Hello @IjzerenHein I just tried the updated module, installed via NPM and it gave me a different error:

    MapView.js:27 Uncaught ReferenceError: define is not defined

I am running in a pure CommonJS environment, and no AMD module loader is being started before, so "define" doesn't exist. Are you using a form of UMD? https://github.com/umdjs/umd The "returnExports" variant seems to work well in these mixed environments.

**Comment by IjzerenHein** [comment]
Hi, I'm sorry I haven't had time to look into this, it's too busy at the moment, hopefully soon.

**Comment by IjzerenHein** [comment]
Hi, I've revamped the whole 'dist' output directory. There is now a 'dist/famous-map-global.js' which you can use for pure CommonJS envionments. This file has been de-amd-ified and supports the following globals:

```javascript
famousmap
famousmap.MapView
famousmap.MapModifier
etc...
```

I will be releasing this shortly in the new v0.3.0 release.

**Comment by antoniobrandao** [comment]
Great, looking forward for it :)

**Comment by IjzerenHein** [comment]
The new release is out!
