### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by antoniobrandao** [IjzerenHein/famous-map#16]
I've been monitoring the performance of this module on an iPhone 5 running iOS8.1, and xCode which tells me the memory and CPU being used.

If I just create one Map, without points, it's effect is almost unnoticeable in the overall CPU usage.

Without the Map, my app reports about 10 / 15% CPU usage, with a Map, my app reports about 15 / 20% CPU usage. The difference is something under 5%.

However if I add markers to the Map - I'm adding about 50 markers - the CPU usage jumps to 70%, without even touching the Map's UI. No interaction at all.

Also I added no Event handlers to the Map.

The points themselves are making the whole difference. Them just sitting there makes the CPU usage jump 50%. Have you noticed this after adding such a number of points? Is high CPU usage expected when adding 50+ points?

The markers are simple surfaces with a small piece of SVG HTML code as "content".

Any idea what may be causing this, or how performance can be improved?

**Comment by IjzerenHein** [comment]
Hi, please read my response posted here #15 

Additionally, when running famo.us as an app on iOS, I strongly suggest using WkWebView. Performance has been increased quite considerably, especially in the Javascript area.
https://github.com/Telerik-Verified-Plugins/WKWebView

**Comment by antoniobrandao** [comment]
Thanks for your input @IjzerenHein !
