### ISSUE TITLE
Mapbox gl support

### ISSUE THREAD

**Issue by dcworldwide** [IjzerenHein/famous-map#9]
Hi, could you please add support for mapbox gl? https://www.mapbox.com/mapbox-gl-js/examples/

I tried but i don't understand how to solve the problem. 

Thanks

**Comment by IjzerenHein** [comment]
Hi, I've added support for Mapbox GL to famous-map.
Cheers.

**Comment by dcworldwide** [comment]
Brilliant thanks :+1: Will test it out.
